export class CheckIn {

}

// CLAUDE GENERATED
export const politicalQuizQuestions: string[] = [
  "How much should the government do to reduce differences in wealth and income between people? Explain what you think is fair and why.",
  "Do you think markets or governments are better at allocating resources like housing, healthcare, and energy? Where, if anywhere, should the other take over?",
  "What role, if any, should labor unions and worker protections play in the economy? Should workers or business owners hold more bargaining power?",
  "Is it ever acceptable for a government to restrict speech? If so, what kinds, and who should decide?",
  "How should a society balance individual privacy against security and surveillance? Describe where you would draw the line.",
  "What do you think the proper role of the state is in a person's private life, such as drug use, relationships, or end-of-life decisions?",
  "How important are tradition and long-standing social norms compared to changing them to reflect new values? Give an example of one you would keep and one you would change.",
  "How do you think society should approach questions of gender, sexuality, and family structure?",
  "What role should religion play in public life, law, and education, if any?",
  "How should a country decide who is allowed to immigrate, and how should it treat people who are already living there?",
  "How much should a nation prioritize its own interests and culture compared to cooperating with other countries and international institutions?",
  "When, if ever, is military force justified? Does your country have a responsibility to intervene abroad?",
  "Do you think power in government is better concentrated in a strong central authority or spread across local communities? Why?",
  "How much should ordinary people vote directly on issues compared to leaving decisions to elected officials or experts?",
  "What is the purpose of the criminal justice system: punishment, deterrence, rehabilitation, or something else? How should that shape sentencing and policing?",
  "How should society address historical injustices and ongoing discrimination against particular groups, if at all?",
  "How far should we go to protect the environment, and who should bear the costs of doing so (individuals, companies, governments, or other countries)?",
  "How should new technologies like AI, social media, and genetic engineering be governed? Who should decide what is allowed?",
  "What do you think about the role of large corporations in society? Should they be broken up, regulated more, regulated less, or left alone?",
  "How much responsibility does an individual have for their own success or failure, as opposed to circumstances and social structures? How should this affect public policy?",
  "If you could change one major thing about how your society is organized, what would it be, and what trade-offs would you accept to do it?",
  "Should healthcare be provided mainly by the government, by private companies, or by some mix? How should people who can't afford care be treated?",
  "How should education be organized and funded? Consider the roles of public schools, private schools, parents, and the state in deciding what children learn.",
  "What do you think of taxation? Describe what you think is a fair tax system, and what, if anything, governments should not tax.",
  "Should the government guarantee a basic standard of living for everyone, through something like a universal basic income or a robust welfare system? What are the risks and benefits?",
  "How should housing be handled? Consider rent, zoning, homeownership, and the government's role in making housing affordable.",
  "Is free trade between countries good or bad for ordinary people? When, if ever, should a country use tariffs or other trade barriers?",
  "How should a society treat the use and sale of drugs, including alcohol and currently illegal substances?",
  "What is your view on private gun ownership, and how should it be regulated, if at all?",
  "How should the law approach abortion, and who should have the final say in that decision?",
  "Should the state ever be allowed to execute people as punishment for crimes? Explain your reasoning, including how you weigh the risk of mistakes.",
  "Do you think people have a right to end their own lives with medical assistance? What limits or safeguards, if any, should apply?",
  "Under what circumstances, if any, is it justified to break the law or disobey the government? Where does legitimate protest end and unacceptable disruption begin?",
  "How much should we trust experts, scientists, and official institutions when they conflict with popular opinion or personal experience?",
  "How should society handle misinformation and harmful content online? Who, if anyone, should decide what people are allowed to post?",
  "What do you think of the role of the media? Should it be regulated, publicly funded, or left entirely to the market?",
  "How much power should courts and judges have to overturn decisions made by elected governments?",
  "What do you think of how your country elects its leaders? What changes, if any, would you make to the electoral system, term limits, or how political campaigns are funded?",
  "How do you feel about patriotism and national pride? Is it a virtue, a danger, or something in between?",
  "Should regions or groups within a country have the right to secede or govern themselves independently? Under what conditions?",
  "How much should wealthy countries do to help poorer countries, through aid, debt relief, or accepting refugees? Where do your obligations to others end?",
  "Should people be allowed to pass on unlimited wealth and property to their children, or should inheritance be limited or taxed heavily?",
  "How should society respond to automation and AI replacing human jobs? Who should benefit from the productivity gains?",
  "What responsibility, if any, do citizens have to serve their country, for example through military or national service, voting, or civic duty?",
  "How should the law treat sex work, gambling, and other activities that some consider immoral but that involve consenting adults?",
  "How do you think we should treat animals? Consider farming, hunting, and animal testing, and explain where you draw moral lines.",
  "How important is preserving a nation's or a community's cultural identity? How should newcomers and minorities relate to the dominant culture?",
  "Do you believe societies are best organized around merit and competition, or around cooperation and shared outcomes? Give an example of where each works best.",
  "How much do you think human nature determines what kind of society is possible? Can people be changed by better institutions, or are some problems permanent?",
  "When a society has deep problems, is it better to pursue gradual reform or radical change? Describe a case where you think each approach is justified.",
];

// CLAUDE GENERATED
export const popCultureQuizQuestions: string[] = [
  "What is the first video game you remember playing, and what do you remember most about it?",
  "Which game world would you most want to live in for a year, and why? What would you do there day to day?",
  "Do you tend to play for story, challenge, exploration, or hanging out with friends? Describe a game that really delivered on what you look for.",
  "What is a game you have replayed many times, and what keeps pulling you back?",
  "When you create a character in a game, how do you build and customize them? Do you pick a type that matches your real self, the opposite, or something totally different?",
  "How do you feel about games that are very hard, like those that punish mistakes? Share a time a game frustrated you or made you proud.",
  "What is your take on cozy games, farming sims, and life sims compared with action or competitive games?",
  "Which gaming soundtrack or piece of game music could you hum right now, and what does it remind you of?",
  "How do you feel about online multiplayer and gaming communities? Describe your best or worst experience.",
  "Handheld, console, PC, or mobile: where do you play most, and what does your setup look like?",
  "Describe your ideal 2000s afternoon: the house, the screen, the snacks, and the sounds in the background.",
  "What was your first experience with the internet, such as chat rooms, instant messaging, forums, or early social sites? What did you do online back then?",
  "Which toy, gadget, or piece of tech from your childhood do you wish you still had?",
  "What cartoons or after-school shows did you watch growing up, and which one shaped your sense of humor the most?",
  "What was the first thing you ever customized or decorated that was yours, like a profile page, a bedroom wall, a ringtone, or a playlist?",
  "Which trend from the 2000s would you bring back without hesitation, and which would you leave in the past?",
  "How did you listen to music growing up, and what physical or digital collection did you have? What did you do with it?",
  "What movie or franchise defined your childhood or teenage years, and how do you feel about it now?",
  "Do you think older games, shows, and tech were better or just feel better because of nostalgia? Make your case.",
  "What is something from your past that you would love to explain to a kid today, such as dial-up, burning CDs, or flip phones, and what would you say?",
  "What is a show you could rewatch endlessly, and what makes it comfort viewing for you?",
  "Do you prefer long, slow-burn series or short, tightly written ones? Describe one you think nailed its pacing.",
  "What is a show or story that you think ended badly, and how would you have ended it?",
  "How do you feel about anime and animation in general? What is one you would recommend to a skeptic?",
  "Which fictional world has the best lore, magic system, or technology? Explain what makes it great.",
  "Who is your favorite fictional character (hero, villain, or sidekick) and what do you connect with about them?",
  "What is your relationship with fantasy and science fiction books, comics, or manga? Describe a series that stuck with you.",
  "Do you prefer shows with a comforting formula or ones that surprise and challenge you? Give examples from your own watch history.",
  "What is a horror, thriller, or mystery story you love, and how do you handle being scared?",
  "How do you feel about reboots, remakes, and adaptations of beloved stories? Name one that worked and one that did not.",
  "How would you describe your personal style right now, and how has it changed over the years?",
  "What items in your wardrobe do you wear constantly, and which are your statement pieces?",
  "Do you wear makeup, grooming products, or accessories as part of your look? Describe your routine or approach, or why you skip it.",
  "What is the best or worst fashion choice you ever made, and what did you learn from it?",
  "How do fictional characters, games, or shows influence the way you dress or present yourself?",
  "What role do hair, nails, piercings, tattoos, or other personal details play in how you express yourself?",
  "Which decade's style, such as 1980s, 1990s, or 2000s, would you most like to dress in for a week? Describe the outfits.",
  "How do you feel about fast fashion, thrifting, and secondhand shopping? What are your habits?",
  "Do you prefer to blend in, stand out, or show only those who know where to look, such as with a band tee, a subtle pin, or a niche reference? Give an example.",
  "Do you tend to follow trends, ignore them, or make your own? Describe a trend you loved and one you avoided.",
  "What fandoms or communities do you consider yourself part of, and how do you participate in them?",
  "Do you collect anything, such as figures, cards, games, books, or merch? What is the story behind your favorite item?",
  "How do you feel about tabletop games, trading card games, and role-playing games? Describe a memorable session or game night.",
  "What is a hobby you got into because of a game, show, or online community? How deep did you go?",
  "Which meme, joke, or piece of internet culture best sums up your sense of humor?",
  "How do you feel about conventions, cosplay, and fan events? Describe one you have attended or would want to.",
  "How do you consume media: streaming, physical copies, or something else? Do you binge or take it slow?",
  "What do you think of fan-made content like fan fiction, mods, fan art, and fan games? Have you ever made any?",
  "How do you handle spoilers, hype, and online discourse about new releases? Describe your approach.",
  "If you could step into any piece of media (game, show, book, or film) for a day as yourself, which would you choose and what would you do?",
  "If someone only knew you through your favorite games, shows, and style, what would they get right about you and what would they miss?",
];
